//
//  WalletsInterfaces.swift
//  iCrypto
//
//  Created by Nghia Nguyen on 6/25/20.
//  Copyright (c) 2020 Nghia Nguyen. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol WalletsWireframeInterface: WireframeInterface {
}

protocol WalletsViewInterface: ViewInterface {
}

protocol WalletsPresenterInterface: PresenterInterface {
}

protocol WalletsFormatterInterface: FormatterInterface {
}

protocol WalletsInteractorInterface: InteractorInterface {
}
