//
//  WalletsPresenter.swift
//  iCrypto
//
//  Created by Nghia Nguyen on 6/25/20.
//  Copyright (c) 2020 Nghia Nguyen. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class WalletsPresenter {

    // MARK: - Private properties -

    private unowned let view: WalletsViewInterface
    private let formatter: WalletsFormatterInterface
    private let interactor: WalletsInteractorInterface
    private let wireframe: WalletsWireframeInterface

    // MARK: - Lifecycle -

    init(view: WalletsViewInterface, formatter: WalletsFormatterInterface, interactor: WalletsInteractorInterface, wireframe: WalletsWireframeInterface) {
        self.view = view
        self.formatter = formatter
        self.interactor = interactor
        self.wireframe = wireframe
    }
}

// MARK: - Extensions -

extension WalletsPresenter: WalletsPresenterInterface {
}
