//
//  ListCurrencyTickerInterfaces.swift
//  iCrypto
//
//  Created by Nguyen Nghia on 8/31/20.
//  Copyright (c) 2020 Nghia Nguyen. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import RxSwift
import Domain

enum ListCurrencyTickerNavigationOption {
    case detail(CurrencyTicker)
}

protocol ListCurrencyTickerWireframeInterface: WireframeInterface {
    func navigate(to option: ListCurrencyTickerNavigationOption)
}

protocol ListCurrencyTickerViewInterface: ViewInterface, ErrorShowable {
    func reloadData()
    func setLoadingVisible(_ visible: Bool)
}

protocol ListCurrencyTickerPresenterInterface: PresenterInterface {
    func getListCurrencyTicker()
    func numberOfSections() -> Int
    func numberOrItems(in section: Int) -> Int
    func item(at indexPath: IndexPath) -> CurrencyTicker?
    func didSelectItem(at indexPath: IndexPath)
}

protocol ListCurrencyTickerInteractorInterface: InteractorInterface {
    func getListCurrencyTicker(currencySymbols: [String]) -> Observable<[CurrencyTicker]>
}
