//
//  ListCurrencyTickerWireframe.swift
//  iCrypto
//
//  Created by Nguyen Nghia on 8/31/20.
//  Copyright (c) 2020 Nghia Nguyen. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import Domain

final class ListCurrencyTickerWireframe: BaseWireframe {

    // MARK: - Private properties -

    private let storyboard = UIStoryboard(name: "ListCurrencyTicker", bundle: nil)

    // MARK: - Module setup -

    init(currencyTickerUseCase: CurrencyTickerUseCase) {
        let moduleViewController = storyboard.instantiateViewController(ofType: ListCurrencyTickerViewController.self)
        super.init(viewController: moduleViewController)

        let interactor = ListCurrencyTickerInteractor(currencyTickerUseCase: currencyTickerUseCase)
        let presenter = ListCurrencyTickerPresenter(view: moduleViewController, interactor: interactor, wireframe: self)
        moduleViewController.presenter = presenter
    }

}

// MARK: - Extensions -

extension ListCurrencyTickerWireframe: ListCurrencyTickerWireframeInterface {
    func navigate(to option: ListCurrencyTickerNavigationOption) {

    }
}
