//
//  DashboardWireframe.swift
//  iCrypto
//
//  Created by Nghia Nguyen on 6/25/20.
//  Copyright (c) 2020 Nghia Nguyen. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class DashboardWireframe: BaseWireframe {

    // MARK: - Private properties -

    private let walletsWireFrame

    // MARK: - Module setup -

    init() {
        let moduleViewController = storyboard.instantiateViewController(ofType: DashboardViewController.self)
        super.init(viewController: moduleViewController)

        let presenter = DashboardPresenter(view: moduleViewController, wireframe: self)
        moduleViewController.presenter = presenter
    }

}

// MARK: - Extensions -

extension DashboardWireframe: DashboardWireframeInterface {
}
