//
//  DashboardInterfaces.swift
//  iCrypto
//
//  Created by Nghia Nguyen on 6/25/20.
//  Copyright (c) 2020 Nghia Nguyen. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol DashboardWireframeInterface: WireframeInterface {
}

protocol DashboardViewInterface: ViewInterface {
}

protocol DashboardPresenterInterface: PresenterInterface {
}
