//
//  DashboardPresenter.swift
//  iCrypto
//
//  Created by Nghia Nguyen on 6/25/20.
//  Copyright (c) 2020 Nghia Nguyen. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class DashboardPresenter {

    // MARK: - Private properties -

    private unowned let view: DashboardViewInterface
    private let wireframe: DashboardWireframeInterface

    // MARK: - Lifecycle -

    init(view: DashboardViewInterface, wireframe: DashboardWireframeInterface) {
        self.view = view
        self.wireframe = wireframe
    }
}

// MARK: - Extensions -

extension DashboardPresenter: DashboardPresenterInterface {
}
