//
//  ListCurrenciesTickerInterfaces.swift
//  iCrypto
//
//  Created by Nguyen Nghia on 8/31/20.
//  Copyright (c) 2020 Nghia Nguyen. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import RxSwift

enum ListCurrenciesTickerNavigationOption {
    case detail(CurrenciesTicker)
}

protocol ListCurrenciesTickerWireframeInterface: WireframeInterface {
    func navigate(to option: ListCurrenciesTickerNavigationOption)
}

protocol ListCurrenciesTickerViewInterface: ViewInterface, ErrorShowable {
    func reloadData()
    func setLoadingVisible(_ visible: Bool)
}

protocol ListCurrenciesTickerPresenterInterface: PresenterInterface {
    func getListCurrenciesTicker()
    func numberOfSections() -> Int
    func numberOrItems(in section: Int) -> Int
    func item(at indexPath: IndexPath) -> CurrenciesTicker?
    func didSelectItem(at indexPath: IndexPath)
}

protocol ListCurrenciesTickerInteractorInterface: InteractorInterface {
    func getListCurrenciesTicker(currenciesSymbols: [String]) -> Observable<[CurrenciesTicker]>
}
