//
//  ListCurrenciesTickerInteractor.swift
//  iCrypto
//
//  Created by Nguyen Nghia on 8/31/20.
//  Copyright (c) 2020 Nghia Nguyen. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Alamofire
import Foundation
import RequestKits
import RxSwift

final class ListCurrenciesTickerInteractor {
    private let currenciesTickerUseCase: CurrenciesTickerUseCase

    init(currenciesTickerUseCase: CurrenciesTickerUseCase) {
        self.currenciesTickerUseCase = currenciesTickerUseCase
    }
}

// MARK: - Extensions -

extension ListCurrenciesTickerInteractor: ListCurrenciesTickerInteractorInterface {
    func getListCurrenciesTicker(currenciesSymbols: [String]) -> Observable<[CurrenciesTicker]> {
        return currenciesTickerUseCase.getListCurrenciesTicker(currenciesSymbols: currenciesSymbols)
    }
}
