//
//  ListCurrenciesTickerViewController.swift
//  iCrypto
//
//  Created by Nguyen Nghia on 8/31/20.
//  Copyright (c) 2020 Nghia Nguyen. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class ListCurrenciesTickerViewController: BaseViewController {
    @IBOutlet private var tableView: UITableView!

    // MARK: - Public properties -

    var presenter: ListCurrenciesTickerPresenterInterface!

    // MARK: - Lifecycle -

    override func viewDidLoad() {
        super.viewDidLoad()
        setupView()
        presenter.getListCurrenciesTicker()
    }

    private func setupView() {
        tableView.delegate = self
        tableView.dataSource = self
        tableView.register(UITableViewCell.self, forCellReuseIdentifier: UITableViewCell.className)
    }
}

// MARK: - Extensions -

extension ListCurrenciesTickerViewController: ListCurrenciesTickerViewInterface {
    func reloadData() {
        tableView.reloadData()
    }
}

extension ListCurrenciesTickerViewController: UITableViewDataSource {
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return presenter.numberOrItems(in: section)
    }

    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let cell = tableView.dequeueReusableCell(withIdentifier: UITableViewCell.className, for: indexPath)
        let currenciesTicker = presenter.item(at: indexPath)
        cell.textLabel?.text = currenciesTicker?.name
        return cell
    }

    func numberOfSections(in tableView: UITableView) -> Int {
        return presenter.numberOfSections()
    }
}

extension ListCurrenciesTickerViewController: UITableViewDelegate {
    func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
        presenter.didSelectItem(at: indexPath)
    }
}
