//
//  ChartsPresenter.swift
//  iCrypto
//
//  Created by Nghia Nguyen on 6/25/20.
//  Copyright (c) 2020 Nghia Nguyen. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class ChartsPresenter {

    // MARK: - Private properties -

    private unowned let view: ChartsViewInterface
    private let formatter: ChartsFormatterInterface
    private let interactor: ChartsInteractorInterface
    private let wireframe: ChartsWireframeInterface

    // MARK: - Lifecycle -

    init(view: ChartsViewInterface, formatter: ChartsFormatterInterface, interactor: ChartsInteractorInterface, wireframe: ChartsWireframeInterface) {
        self.view = view
        self.formatter = formatter
        self.interactor = interactor
        self.wireframe = wireframe
    }
}

// MARK: - Extensions -

extension ChartsPresenter: ChartsPresenterInterface {
}
